apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ${name}
  namespace: kube-system
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${private_key_secret}
    solvers:
    - selector:
        dnsZones:
%{ for zone in dns_zones ~}
        - "${zone}"
%{ endfor ~}
      dns01:
        route53:
          region: ${aws_region}
          hostedZoneID: ${hosted_zone_id}
          role: ${iam_role_arn}
