apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ${name}
  namespace: kube-system
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${private_key_secret}
    solvers:
    - dns01:
        route53:
          region: ${aws_region}
          hostedZoneID: ${hosted_zone_id}
          role: ${iam_role_arn}

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ${name}-ca
  namespace: kube-system
spec:
  secretName: ${app_name}-ca-tls
  commonName: "${app_name}"
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: ${name}
