apiVersion: cert-manager.io/v1alpha2
kind: ${issuer_type}
metadata:
  name: ${name}
%{ if issuer_type != "ClusterIssuer" ~}
  namespace: ${k8s_namespace}
%{ endif ~}
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${private_key_secret}
    solvers:
    - dns01:
        route53:
          region: ${aws_region}
          hostedZoneID: ${hosted_zone_id}
%{ if set_assume_config ~}
          role: ${iam_role_arn}
%{ endif ~}
